### PR TITLE
Fix/add handling of empty data and complex layer name

### LINKED ISSUE #65: Add handling of empty data sets and multi-part layer names for ArcGIS SDE plugin

### PR DESCRIPTION
**Pull request by sweco-se1g7y**
Implemented a fix for some situations that created problems in Eskilstuna's environment.

Resolve #65

### CODE REVIEW

File: plugins/arcgis-sde-data-common/src/index.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export interface DomainValue {
 
 export interface ArcGISSDEDomainEntity extends Entity {
   apiVersion: 'geoportia.se/v1alpha1';
-  kind: 'Table';
+  kind: 'ArcGISDomain';
```
Comment (sweco-sedalh) [inline plugins/arcgis-sde-data-common/src/index.ts]: As with tables, domains (and domain values) should be more generic, as they also exist in other databases. The `dialect`-pattern can be reused here.

**Review by sweco-sedalh — CHANGES_REQUESTED** [review]

File: plugins/arcgis-sde-data-common/src/index.ts (hunk 1 above)
Comment (sweco-se1g7y) [reply plugins/arcgis-sde-data-common/src/index.ts]: Fixed!

**Review by sweco-sedalh — APPROVED** [review]
